### ISSUE TITLE
Need help in getting metrics on container start-up time when replica is zero and one.

### ISSUE THREAD

**Issue by tshravan86** [openfaas/workshop#137]
Hi,

I'm having a bit trouble in understanding how to get the metrics. I need information regarding,

- How much time it takes to execute a function which is in cold and warm state.

- How much time the function takes to complete its process.

I have gone through the metrics section in official documentation.

`gateway_functions_seconds`

I'm confused whether it does gives us the start-up time of our function. I'm getting the message "No data points found".
Can you please help me out and point me to the right direction? Thanks a lot.

<img width="1273" alt="Screenshot at Aug 01 17-29-39" src="https://user-images.githubusercontent.com/45789078/62291639-0f7b5580-b482-11e9-8f22-3ba0f9f2819c.png">

**Comment by alexellis** [comment]
Hi @tshravan86 

Thank you for your interest in the project.

The metrics are explained in detail in the docs and you may prefer to use the dashboard outlined in the labs, rather than Prometheus directly.

https://docs.openfaas.com/architecture/metrics/

https://github.com/openfaas/workshop/blob/master/lab2.md#monitoring-dashboard

Alex

**Comment by alexellis** [comment]
--
Join Slack to connect with the community
https://docs.openfaas.com/community

**Comment by tshravan86** [comment]
Thank you @alexellis
