### ISSUE TITLE
Lab 1B script to download arkade for windows  is wrong

### ISSUE THREAD

**Issue by Jeff-Lowrey** [openfaas/workshop#174]
The command listed in the Lab 1B of the workshop to download arkade for windows is 
`curl -SLsf https://dl.get-arkade.dev/ | sh`

It is reasonable to expect that curl is available on windows.  But the same can't be said of sh.

The script at https://dl.get-arkade.dev also does not know anything about windows.

So the Lab 1B readme should be updated with the proper steps to fetch the windows binary. Something like
`curl -SLsf https://alexellis/arkade/releases/download/<release>/arkade.exe` 

or a curl command that gets and runs a Windows cmd script or Powershell script that will figure out what the current release is and download the relevant binary,

**Comment by alexellis** [comment]
Hi Jeff,

Thanks for your interest however, I think you may have missed that we ask users to install Git Bash in order to follow the workshop on Windows, you'll see that documented here:

https://github.com/openfaas/workshop/blob/master/lab1.md

There is no plan to have support for Powershell or cmd.exe when Git Bash works perfectly well.

Alex
