### ISSUE TITLE
Lab 5: Ngrok Tunnel commands are not working

### ISSUE THREAD

**Issue by DanielHabenicht** [openfaas/workshop#196]
## Expected Behaviour
Works

## Current Behaviour
Errors: 

![image](https://user-images.githubusercontent.com/13590797/117932540-c3b93980-b300-11eb-8b1c-46f55747e4a9.png)

## Possible Solution

```bash
# Use Pod instead of deployment
$ kubectl -n openfaas run \
--image=alexellis2/ngrok-admin \
--port=4040 \
ngrok -- http gateway:8080

$ kubectl -n openfaas expose pod ngrok \
--type=NodePort \
--name=ngrok

$ kubectl port-forward pod/ngrok 4040:4040 -n openfaas
```

**Comment by DanielHabenicht** [comment]
Also, this section here is somewhat not coherent: 
![image](https://user-images.githubusercontent.com/13590797/117933216-9caf3780-b301-11eb-9df3-f2a7b5308723.png)

The second command should make use of the environment variable. 

I can provide a PR if someone approves my suggestion.

**Comment by alexellis** [comment]
Hi @DanielHabenicht let's switch it to inlets, at least we know that the project supports containers and Kubernetes and has a well-defined user experience. This failed due to the hacks we had to go through to force Ngrok to play nicely in containers. It's just not a goal they have. inlets cloud native first and has a subscription model, so it's easy to try it out with minimum cost.
